//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPC_FEEDBACK_CATEGORY
    {
        public decimal ID { get; set; }
        public decimal PROJECTID { get; set; }
        public string VALUE { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
    }
}
