//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPC_FEEDBACK
    {
        public decimal ID { get; set; }
        public decimal PROJECTID { get; set; }
        public decimal PRIORITYID { get; set; }
        public decimal STATUSID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string RESOLUTION { get; set; }
        public string ASSIGNED_BY { get; set; }
        public string ASSIGNED_TO { get; set; }
        public Nullable<System.DateTime> DATE_ASSIGNED { get; set; }
        public Nullable<System.DateTime> DATE_RESOLVED { get; set; }
        public string UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<decimal> CATEGORYID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
