//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPC_FEEDBACK_PROJUSERS
    {
        public decimal ID { get; set; }
        public decimal PROJECTID { get; set; }
        public string USERID { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
