//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPC_FEEDBACK_USERS
    {
        public string USERID { get; set; }
        public string USERLEVEL { get; set; }
        public string EMAIL { get; set; }
        public string NAME { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> LOCKED { get; set; }
        public string LOCATIONLDAP { get; set; }
        public string OU { get; set; }
        public string MANAGER { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
    }
}
