//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PHRASE_TRANSLATIONS
    {
        public decimal F_TRANSLATION_ID { get; set; }
        public decimal F_PHRASE_ID { get; set; }
        public string F_LANGUAGE { get; set; }
        public string F_PHRASE { get; set; }
        public string F_COMMENTS { get; set; }
        public string F_USER_REQUESTED { get; set; }
        public string F_USER_ADDED { get; set; }
        public string F_USER_UPDATED { get; set; }
        public System.DateTime F_DATE_STAMP { get; set; }
    }
}
