//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROD_WITH_INPUT_PROD_GROUPS
    {
        public string F_PRODUCT { get; set; }
        public string F_INPUT_PRODUCT { get; set; }
        public short F_GROUPID { get; set; }
        public short F_REQUIRED { get; set; }
    
        public virtual T_PROD_WITH_INPUT_PROD T_PROD_WITH_INPUT_PROD { get; set; }
    }
}
