//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROD_TEXT
    {
        public string F_PRODUCT { get; set; }
        public string F_FORMAT { get; set; }
        public string F_TEXT_CODE { get; set; }
        public Nullable<System.DateTime> F_DATE_STAMP { get; set; }
        public string F_DATA_CODE { get; set; }
        public Nullable<int> F_COUNTER { get; set; }
        public string F_USER_UPDATED { get; set; }
        public string F_JOIN_BY { get; set; }
    }
}
