//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_PICKLISTS
    {
        public string VALUE { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public int ID { get; set; }
        public string TYPE { get; set; }
    }
}
