//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_RAD_SHIP
    {
        public string MODEL_NO { get; set; }
        public string SERIAL_NO { get; set; }
        public decimal SHIPID { get; set; }
        public decimal SORT_ORDER { get; set; }
        public decimal CONFIG_ID { get; set; }
    
        public virtual WSSE_SHIP WSSE_SHIP { get; set; }
    }
}
