//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_SHIP_KINETIX_VW
    {
        public decimal ID { get; set; }
        public Nullable<decimal> RADIOACTIVE { get; set; }
        public Nullable<decimal> COLORADO { get; set; }
        public string WELLSITE { get; set; }
        public string DISTRICT { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public string TREATMENT { get; set; }
        public string TRUCK_NO { get; set; }
        public string TRAILER_NO { get; set; }
        public string CUSTOMER { get; set; }
        public string LOCATION { get; set; }
        public string WELL { get; set; }
        public string INSTRUCTIONS { get; set; }
        public string SAFETY { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<decimal> LOAD_DIFF { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string SUPERVISOR { get; set; }
        public string USERID { get; set; }
        public string CERT_SIGN { get; set; }
        public string LOAD_SIGN { get; set; }
        public string TMP_EDIT { get; set; }
        public string CREATE_BY { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string STOP_NUMBER { get; set; }
        public string ORIGIN { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<decimal> NUM_OF_PRODUCTS_TMS { get; set; }
        public decimal ARCHIVED { get; set; }
        public string CAT { get; set; }
        public string PROD_CODE { get; set; }
        public string ORDER_RELEASE_ID { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public string ACTUAL_UNIT { get; set; }
        public string PACKTYPE { get; set; }
        public string PACKLOC { get; set; }
        public Nullable<decimal> PACKNO { get; set; }
        public string BULKITEM { get; set; }
        public Nullable<decimal> DOTSHIPID { get; set; }
        public string LOTNO { get; set; }
        public string TANKNO { get; set; }
        public string SLINGNO { get; set; }
        public Nullable<System.DateTime> SLINGDATE { get; set; }
        public Nullable<short> RESIDUE { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string MODEL_DESC { get; set; }
        public string SERIAL_NO { get; set; }
        public Nullable<decimal> SORT_ORDER { get; set; }
        public Nullable<decimal> CONFIG_ID { get; set; }
        public string CONFIG_NAME { get; set; }
    }
}
