//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_RAD_CONFIG
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> DISABLE_ALL { get; set; }
        public string INCLUDE { get; set; }
        public Nullable<decimal> SORT_ORDER { get; set; }
    }
}
