//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_RAD_LABELS
    {
        public string MODEL_DESC { get; set; }
        public string LABEL { get; set; }
        public string HAZ_TYPE { get; set; }
        public string IMAGE_NAME { get; set; }
        public decimal ID { get; set; }
    }
}
