//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_TMS_PRODUCTS
    {
        public string SHIPMENT_ID { get; set; }
        public string SOURCE { get; set; }
        public string DESTINATION { get; set; }
        public string STOP_NUMBER { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string DATESTAMP { get; set; }
        public decimal SHIPID { get; set; }
        public decimal ISDELETED { get; set; }
    }
}
