//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_LOGGER
    {
        public decimal LOGGER_ID { get; set; }
        public Nullable<System.DateTime> LOGGER_DATE { get; set; }
        public string LOGGER_LOCATION { get; set; }
        public string LOGGER_IP { get; set; }
        public Nullable<decimal> LOGGER_EXECUTION_TIME { get; set; }
        public Nullable<decimal> LOGGER_DOC_COUNT { get; set; }
        public string LOGGER_PAGE_TYPE { get; set; }
        public string LOGGER_ALIAS { get; set; }
        public string LOGGER_BROWSER { get; set; }
    }
}
