//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_RAD_DETAILS
    {
        public string MODEL_DESC { get; set; }
        public string SHIP_DESC { get; set; }
        public string RADIONUCLIDE { get; set; }
        public string TRANSPORT_INDEX { get; set; }
        public string PACKAGE_TYPE { get; set; }
        public decimal ID { get; set; }
        public string ACTIVITY { get; set; }
        public string GROSS_WT { get; set; }
    }
}
