//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.USSP.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSE_SHIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WSSE_SHIP()
        {
            this.WSSE_DOT_SHIP = new HashSet<WSSE_DOT_SHIP>();
            this.WSSE_MAT_SHIP = new HashSet<WSSE_MAT_SHIP>();
            this.WSSE_RAD_SHIP = new HashSet<WSSE_RAD_SHIP>();
        }
    
        public decimal ID { get; set; }
        public string WELLSITE { get; set; }
        public string DISTRICT { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public string TREATMENT { get; set; }
        public string TRUCK_NO { get; set; }
        public string TRAILER_NO { get; set; }
        public string CUSTOMER { get; set; }
        public string LOCATION { get; set; }
        public string WELL { get; set; }
        public string INSTRUCTIONS { get; set; }
        public string EXEMPT { get; set; }
        public string SAFETY { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string SUPERVISOR { get; set; }
        public string USERID { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> LOAD_DIFF { get; set; }
        public string TMP_EDIT { get; set; }
        public string CERT_SIGN { get; set; }
        public string LOAD_SIGN { get; set; }
        public short RADIOACTIVE { get; set; }
        public decimal ARCHIVED { get; set; }
        public decimal COLORADO { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string STOP_NUMBER { get; set; }
        public string ORIGIN { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<decimal> NUM_OF_PRODUCTS_TMS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WSSE_DOT_SHIP> WSSE_DOT_SHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WSSE_MAT_SHIP> WSSE_MAT_SHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WSSE_RAD_SHIP> WSSE_RAD_SHIP { get; set; }
        public virtual WSSE_USER WSSE_USER { get; set; }
    }
}
